apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: ltche
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/ltche-harbor-project/db@sha256:93f1fe08e3cc37959c033c64b8029c712a4e81051b7b97437c3552c723ab6a56
        ports:
        - containerPort: 5432
